import { World } from '../types';
import { darkFantasy } from '../themes/darkFantasy';

export const seedWorld: World = {
  id: 'world_01',
  name: 'The Shattered Realm',
  description: 'A world of warring factions and ancient magic, shattered by the Sundering.',
  nodes: {
    n_aragath: {
      id: 'n_aragath',
      type: 'character',
      title: 'Aragath the Undying',
      slug: 'aragath-the-undying',
      content: `## Overview\n\nAragath is the immortal sorcerer-king who rules the [[Obsidian Throne]]. He was the architect of the [[The Sundering]].\n\n## Appearance\n\nTall, gaunt, with eyes that glow a pale amber. Wears robes of deep violet trimmed with bone.\n\n## Goals & Motivations\n\nSeeks to undo the Sundering he caused — though his methods are as destructive as the original catastrophe.`,
      excerpt: 'Aragath is the immortal sorcerer-king who rules the Obsidian Throne. He was the architect of the Sundering.',
      tags: ['immortal', 'sorcerer', 'antagonist'],
      links: ['n_throne', 'n_sundering'],
      metadata: {
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
        icon: '🧙',
        pinned: true,
      },
    },
    n_throne: {
      id: 'n_throne',
      type: 'location',
      title: 'Obsidian Throne',
      slug: 'obsidian-throne',
      content: `## Overview\n\nThe seat of power in the [[Shattered Reaches]], held by [[Aragath the Undying]] for three centuries.\n\n## Atmosphere\n\nA fortress of black glass, rising from an ashen plain. The air smells of ozone. The throne itself hums with imprisoned souls.`,
      excerpt: 'The seat of power in the Shattered Reaches, held by Aragath the Undying for three centuries.',
      tags: ['fortress', 'seat-of-power'],
      links: ['n_aragath', 'n_reaches'],
      metadata: {
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
        icon: '🏰',
      },
    },
    n_sundering: {
      id: 'n_sundering',
      type: 'event',
      title: 'The Sundering',
      slug: 'the-sundering',
      content: `## Summary\n\nThree hundred years ago, [[Aragath the Undying]] attempted a ritual to achieve true godhood. The ritual failed catastrophically, splitting the continent and destroying the old world.\n\n## Consequences\n\n- The continent fractured into floating islands\n- Magic became unstable and dangerous\n- The [[Order of the Mended World]] was founded to prevent another Sundering`,
      excerpt: 'Three hundred years ago, Aragath the Undying attempted a ritual to achieve true godhood, splitting the continent.',
      tags: ['cataclysm', 'history', 'magic'],
      links: ['n_aragath', 'n_order'],
      metadata: {
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
        icon: '⚡',
      },
    },
    n_order: {
      id: 'n_order',
      type: 'faction',
      title: 'Order of the Mended World',
      slug: 'order-of-the-mended-world',
      content: `## Overview\n\nA secretive order founded in the aftermath of the [[The Sundering]]. Their goal is to find the Mending Stones and reverse the damage done.\n\n## Leadership\n\nLed by the Archweaver, currently [[Selan Orveth]].\n\n## Allies & Enemies\n\nEnemy of [[Aragath the Undying]], who seeks the Mending Stones for his own purposes.`,
      excerpt: 'A secretive order founded in the aftermath of the Sundering. Their goal is to find the Mending Stones and reverse the damage done.',
      tags: ['order', 'mages', 'protagonists'],
      links: ['n_sundering', 'n_selan', 'n_aragath'],
      metadata: {
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
        icon: '⚔️',
      },
    },
    n_selan: {
      id: 'n_selan',
      type: 'character',
      title: 'Selan Orveth',
      slug: 'selan-orveth',
      content: `## Overview\n\nArchweaver of the [[Order of the Mended World]]. A half-elf scholar who has dedicated her life to unraveling the mystery of the [[The Sundering]].\n\n## Personality\n\nCalm, methodical, and deeply cautious. Distrusts anyone who uses magic recklessly.`,
      excerpt: 'Archweaver of the Order of the Mended World. A half-elf scholar who has dedicated her life to unraveling the mystery of the Sundering.',
      tags: ['mage', 'leader', 'half-elf'],
      links: ['n_order', 'n_sundering'],
      metadata: {
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
        icon: '👤',
      },
    },
    n_reaches: {
      id: 'n_reaches',
      type: 'location',
      title: 'Shattered Reaches',
      slug: 'shattered-reaches',
      content: `## Overview\n\nThe largest floating continent fragment, now ruled from the [[Obsidian Throne]].\n\n## Geography\n\nRugged highlands and deep chasms. The edges of the island crumble slowly into the Void Below.`,
      excerpt: 'The largest floating continent fragment, now ruled from the Obsidian Throne.',
      tags: ['continent', 'location'],
      links: ['n_throne'],
      metadata: {
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
        icon: '📍',
      },
    },
  },
  edges: [
    { id: 'e_01', source: 'n_aragath', target: 'n_order', label: 'enemy of', type: 'directed' },
    { id: 'e_02', source: 'n_selan', target: 'n_aragath', label: 'opposes', type: 'directed' },
    { id: 'e_03', source: 'n_aragath', target: 'n_throne', label: 'rules from', type: 'directed' },
    { id: 'e_04', source: 'n_throne', target: 'n_reaches', label: 'located in', type: 'directed' },
  ],
  theme: darkFantasy,
  settings: {
    autoLink: false,
    graphPhysics: false,
    clusterByType: false,
    defaultNodeType: 'character',
    autoSave: true,
    saveIntervalMs: 500,
  },
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',
  version: 1,
};
